/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* Tue Jul 19 18:10:50 2022 */

/* parameterized module instance */
FIFO __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .WCNT( ), .Empty( ), .Full( ));
